# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pw_hash',
            new_name='password',
        ),
    ]
