# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catergory',
            new_name='category',
        ),
    ]
